#!/bin/sh

# userresources=$HOME/.Xresources
# usermodmap=$HOME/.Xmodmap
# sysresources=/etc/X11/xinit/.Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap
# 
# # merge in defaults and keymaps
# 
# if [ -f $sysresources ]; then
#     xrdb -merge $sysresources
# fi
# 
# if [ -f $sysmodmap ]; then
#     xmodmap $sysmodmap
# fi
# 
# if [ -f "$userresources" ]; then
#     xrdb -merge "$userresources"
# fi
# 
# if [ -f "$usermodmap" ]; then
#     xmodmap "$usermodmap"
# fi
# 
xset r rate 175 50
xbanish & disown

setxkbmap -layout us,ru -option grp:alt_shift_toggle
